### ISSUE TITLE
Typescript 2.0.6 update seems to break typescript-formatting..

### ISSUE THREAD

**Issue by wsager** [vvakame/typescript-formatter#65] opened 2016-10-25 22:19 UTC
Was previously using ts 2.0.3 and tsFmt 3.0.1, using tsFmt.json file.

After typescript module was updated to 2.0.6, all typescript files are now left-justified with no indents.

Attaching tsFmt.json file.

command line for typescript formatter was:
../../../node_modules/.bin/tsfmt --replace --baseDir "." --no-tslint --no-editorconfig
[tsfmt.json.txt](https://github.com/vvakame/typescript-formatter/files/551929/tsfmt.json.txt)

**Comment by alexbyk** [comment] 2016-10-26 01:20
+1

**Comment by mhegazy** [comment] 2016-10-26 21:28
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/11852.

**Comment by vvakame** [comment] 2016-10-27 02:45
wow.

I just published `typescript-formatter@4.0.0`. It supports `typescript@2.0.6`.
https://github.com/Microsoft/TypeScript/blame/06afadda727dbe786ada964f939b16bf45fd28e6/src/services/types.ts#L413

**Closed by vvakame** 2016-10-27 02:45 UTC

**Comment by jvanoostveen** [comment] 2016-11-01 09:20
`typescript-formatter@4.0.0` now no longer supports `typescript@2.0.3`, is this intentional or should 4.0.0 also work with 2.0.3?

**Comment by jvanoostveen** [comment] 2016-11-01 09:24
Ah sorry, just read the changelog, in short yes...
Because of issues with typescript 2.0.6 self we downgraded, but did not yet downgrade the formatter. We now downgraded both.
